package pl.emsoSecurity.authapp.constants;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public final class PidConstants {
    private PidConstants() {
        // restrict instantiation
    }

    public static final Map<Integer, String> pidDecimalToHexMap = initMap();

    /***
     * Map consisting of the relation between the Decimal PID and the PID Description.
     * @return
     */
    private static Map<Integer, String> initMap() {
        Map<Integer, String> map = new HashMap<>();
        map.put(1, "Dev TS");
        map.put(2, "VIN");
        map.put(10, "Gps Latitude");
        map.put(11, "Gps Longitude");
        map.put(12, "Gps altitude");
        map.put(13, "Gps Speed");
        map.put(15, "Gps Satellite Count");
        map.put(16, "Gps time");
        map.put(17, "Gps date");
        map.put(32, "Gps Acc");
        map.put(36, "Battery Voltage");
        map.put(37, "Orientation");
        map.put(259, "Fuel System Status");
        map.put(260, "Calculated Engine Load");
        map.put(261, "Engine Coolant Temperature");
        map.put(262, "Short Term Fuel Trim - Bank 1");
        map.put(263, "Long Term Fuel Trim - Bank 1");
        map.put(264, "Short Term Fuel Trim - Bank 2");
        map.put(265, "Long Term Fuel Trim - Bank 2");
        map.put(266, "Fuel Pressure");
        map.put(267, "Intake Manifold Absolute Pressure");
        map.put(268, "Engine Speed");
        map.put(269, "Vehicle Speed");
        map.put(270, "Timing Advance");
        map.put(271, "Intake Air Temperature");
        map.put(272, "Mass Airflow Sensor");
        map.put(273, "Throttle Position");
        map.put(274, "Commanded Secondary Air Status");
        map.put(275, "Oxygen Sensors in 2 Banks");
        map.put(276, "Oxygen Sensor 1");
        map.put(277, "Oxygen Sensor 2");
        map.put(278, "Oxygen Sensor 3");
        map.put(279, "Oxygen Sensor 4");
        map.put(280, "Oxygen Sensor 5");
        map.put(281, "Oxygen Sensor 6");
        map.put(282, "Oxygen Sensor 7");
        map.put(283, "Oxygen Sensor 8");
        map.put(284, "OBD Standard Confirmation");
        map.put(285, "Oxygen Sensors in 4 Banks");
        map.put(286, "AUX Input Status");
        map.put(287, "Runtime");
        map.put(288, "PIDs Supported (21-40)");
        map.put(289, "Distance Travelled with Malfunction");
        map.put(290, "Fuel Rail Pressure");
        map.put(291, "Fuel Rail Gauge Pressure");
        map.put(292, "Oxygen Sensor 1");
        map.put(293, "Oxygen Sensor 2");
        map.put(294, "Oxygen Sensor 3");
        map.put(295, "Oxygen Sensor 4");
        map.put(296, "Oxygen Sensor 5");
        map.put(297, "Oxygen Sensor 6");
        map.put(298, "Oxygen Sensor 7");
        map.put(299, "Oxygen Sensor 8");
        map.put(300, "Commanded EGR");
        map.put(301, "EGR Error");
        map.put(302, "Commanded Evaporative Purge");
        map.put(303, "Fuel Tank Level");
        map.put(304, "Warmups");
        map.put(305, "Distance Travelled Since Codes Cleared");
        map.put(306, "Evap. System Vapour Pressure");
        map.put(307, "Absolute Barometric Pressure");
        map.put(308, "Oxygen sensor 1");
        map.put(309, "Oxygen sensor 2");
        map.put(310, "Oxygen sensor 3");
        map.put(311, "Oxygen sensor 4");
        map.put(312, "Oxygen sensor 5");
        map.put(313, "Oxygen sensor 6");
        map.put(314, "Oxygen sensor 7");
        map.put(315, "Oxygen sensor 8");
        map.put(316, "Catalyst Temperature Bank 1 Sensor 1");
        map.put(317, "Catalyst Temperature Bank 2 Sensor 1");
        map.put(318, "Catalyst Temperature Bank 1 Sensor 2");
        map.put(319, "Catalyst Temperature Bank 2 Sensor 2");
        map.put(320, "PIDs Supported(41-60)");
        map.put(321, "Monitor Status This Drive Cycle");
        map.put(322, "Control Module Voltage");
        map.put(323, "Absolute Load Value");
        map.put(324, "Commanded Air Fuel Equivalence Ratio");
        map.put(325, "Relative Throttle Position");
        map.put(326, "Ambient Air Temperature");
        map.put(327, "Absolute Throttle Position B");
        map.put(328, "Absolute Throttle Position 3");
        map.put(329, "Absolute Throttle Position D");
        map.put(330, "Absolute Throttle Position E");
        map.put(331, "Absolute Throttle Position F");
        map.put(332, "Commanded Throttle Actuator");
        map.put(333, "Time Run with MIL on");
        map.put(334, "Time Since Travel Codes Cleared");
        map.put(335, "Max Value for Fuel Air Eqv");
        map.put(336, "Max Value for Air Flow");
        map.put(337, "Fuel Tire");
        map.put(338, "Ethanol fuel %");
        map.put(339, "Abs. Evap. System Vap. Pressure");
        map.put(340, "Evap. System Vap. Pressure");
        map.put(341, "Short Term Secondary O2 Sensor A: Bank 1 B: bank 3");
        map.put(342, "Long Term Secondary O2 Sensor A: Bank 1 B: bank 3");
        map.put(343, "Short Term Secondary O2 Sensor A: Bank 2 B: bank 4");
        map.put(344, "Long Term Secondary O2 Sensor A: Bank 2 B: bank 4");
        map.put(345, "Fuel Rail Absolute Pressure");
        map.put(346, "Relative Accelerator Pedal Position");
        map.put(347, "Hybrid Battery Pack Remaining Life");
        map.put(348, "Engine Oil Temperature");
        map.put(349, "Fuel Injection Timing");
        map.put(350, "Engine Fuel Rate");
        map.put(351, "Emission Req. of Veh. Design");
        map.put(352, "PIDs Supported (61-80)");
        map.put(353, "Driver's Demand Engine - Percent Torque");
        map.put(354, "Actual Engine - Percent Torque");
        map.put(355, "Engine Reference Torque");
        map.put(356, "Engine Percent Torque Data");
        map.put(357, "Auxiliary Input/ Output supported");
        map.put(358, "Mass Air Flow Sensor");
        map.put(359, "Engine Coolant Temperature");
        map.put(360, "Intake Air Temperature Sensor");
        map.put(361, "Commanded EGR and EGR Error");
        map.put(362, "Commanded Diesel Intake air flow control and relative intake air flow position");
        map.put(363, "Exhaust Gas Recirculation Temperature");
        map.put(364, "Commanded Throttle Actuator Control and Relative Throttle position");
        map.put(365, "Fuel Pressure control system");
        map.put(366, "Injection pressure control system");
        map.put(367, "Turbocharger compressor Inlet Pressure");
        map.put(368, "Boost pressure control");
        map.put(369, "Variable Geometry turbo (VGT) control");
        map.put(370, "Wastegate control");
        map.put(371, "Exhaust Pressure");
        map.put(372, "Turbocharger RPM");
        map.put(373, "Turbocharger temperature");
        map.put(374, "Turbocharger temperature");
        map.put(375, "Charge air cooler temperature (CACT)");
        map.put(376, "Exhaust Gas Temperature (EGT) Bank 1");
        map.put(377, "Exhaust Gas Temperature (EGT) Bank 2");
        map.put(378, "Diesel Particulate Filter (DPF)");
        map.put(379, "Diesel Particulate Filter (DPF)");
        map.put(380, "Diesel Particulate Filter (DPF) temperature");
        map.put(381, "NOx NTE(Not-To-Exceed) control area status");
        map.put(382, "PM NTE(Not-To-Exceed) control area status");
        map.put(383, "Engine Run Time [b]");
        map.put(384, "PIDs supported [81-A0]");
        map.put(385, "Engine run time for Auxiliary Emissions Control Device(AECD)");
        map.put(386, "Engine run time for Auxiliary Emissions Control Device(AECD)");
        map.put(387, "NOx Sensor");
        map.put(388, "Manifold Surface Temperature");
        map.put(389, "NOx reagent system");
        map.put(390, "Particulate Matter (PM) sensor");
        map.put(391, "Intake manifold absolute pressure");
        map.put(392, "SCR induce System");
        map.put(393, "Run Time for AECD#11-#15");
        map.put(394, "Run Time for AECD#16-#20");
        map.put(395, "Diesel Aftertreatment");
        map.put(396, "O2 sensor (Wide Range)");
        map.put(397, "Throttle Position G");
        map.put(398, "Engine Friction-Percent Torque");
        map.put(399, "PM Sensor Bank 1 & 2");
        map.put(400, "WWH-OBD Vehicle OBD System Information");
        map.put(401, "WWH-OBD Vehicle OBD System Information");
        map.put(402, "Fuel System Control");
        map.put(403, "WWH-OBD Vehicle OBD Counters support");
        map.put(404, "NOx Warning And Inducement System");
        map.put(405, "Emission Requirements to which vehicle is designed");
        map.put(406, "PIDs supported [61-80]");
        map.put(407, "Driver's demand engine-percent torque");
        map.put(408, "Exhaust Gas Temperature Sensor");
        map.put(409, "Exhaust Gas Temperature Sensor");
        map.put(410, "Hybrid/EV Vehicle System Data, Battery, Voltage");
        map.put(411, "Diesel Exhaust Fluid Sensor Data");
        map.put(412, "O2 Sensor Data");
        map.put(413, "Engine Fuel Rate");
        map.put(414, "Engine Exhaust Flow Rate");
        map.put(415, "Fuel System Percentage Use");
        map.put(416, "PIDs Supported [A1-C0]");
        map.put(417, "NOx Sensor Corrected Data");
        map.put(418, "Cylinder Fuel Rate");
        map.put(419, "Evap System Vapor Pressure");
        map.put(420, "Transmission Actual Gear");
        map.put(421, "Diesel Exhaust Fluid Dosing");
        map.put(422, "Odometer");
        map.put(448, "PIDs supported [C1-E0]");

        return Collections.unmodifiableMap(map);
    }

}
